/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Tokenizer {
  model: string
  constructor(model: string)
  countTokens(text: string): number
  getContextSize(): number
}
